name: Publish NPM Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21' # Set this to your Node.js version
          registry-url: 'https://registry.npmjs.org/'
      - name: Set up Git identity
        run: |
          git config --local user.email "bryan@bryanp.xyz"
          git config --local user.name "Bryan Parker"
      - run: npm ci
      - run: npm run vite-npm-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
