name: Publish NPM Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21' # Set this to your Node.js version
          registry-url: 'https://registry.npmjs.org/'
      - run: npm run publish-to-npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
